-- 01. CAR 테이블 생성
CREATE TABLE CAR(
    CAR_ID CHAR(10), 
    CAR_NAME VARCHAR2(30),
    CAR_MAKER VARCHAR2(30),
    CAR_MAKE_YEAR NUMBER(4),
    CAR_PRICE NUMBER(5) 
);

-- 자동차 제조사 조회 / 중복 내용 제거
SELECT DISTINCT CAR_MAKER FROM CAR;

-- 제조사 코드 형식 AA-0-000
SELECT DBMS_RANDOM.STRING('X',2) || '-' ||
	TRUNC(DBMS_RANDOM.VALUE(0,10),0) || '-' ||
	TRUNC(DBMS_RANDOM.VALUE(100,1000),0)
FROM DUAL;

-- 02. 자동차 제조사 테이블 생성
--자동차 제조사 테이블 생성
CREATE TABLE CAR_MAKER
AS 
SELECT 
DBMS_RANDOM.STRING('X',2) || '-' ||
	TRUNC(DBMS_RANDOM.VALUE(0,10),0) || '-' ||
	TRUNC(DBMS_RANDOM.VALUE(100,1000),0) AS CAR_MARER_CODE
,CAR_MAKER AS CAR_MAKER_NAME
FROM (SELECT DISTINCT CAR_MAKER FROM CAR);

--자동차 테이블에 제조사 코드 컬럼 추가
ALTER TABLE CAR ADD CAR_MAKER_CODE VARCHAR2(10);

UPDATE CAR C SET C.CAR_MAKER_CODE = 
(SELECT CM.CAR_MAKER_CODE 
	FROM CAR_MAKER CM
	WHERE C.CAR_MAKER = CM.CAR_MAKER_NAME);

--자동차 테이블에 제조사명 컬럼을 삭제
ALTER TABLE CAR DROP COLUMN CAR_MAKER;


-- 03. 자동차 판매 테이블 생성
CREATE TABLE CAR_SELL(
    CAR_SELL_NO NUMBER PRIMARY KEY,
    CAR_ID VARCHAR2(10),
    CAR_SELL_EA NUMBER(3),
    CAR_SELL_PRICE NUMBER(10),
    CAR_SELL_DATE DATE DEFAULT SYSDATE
);
